### ISSUE TITLE
jupyter-forward prompting for password even though I have ssh keys?

### ISSUE THREAD

**Issue by jessecusack** [ncar-xdev/jupyter-forward#112]
I have set up ssh key access to Rutger's local HPC cluster amarel. Commands like `ssh amarel` log me in instantaneously, so long as I am on the unversity network or VPN. I have specified `amarel` in the `.ssh/config` as:

```
Host amarel
    Hostname amarel.rutgers.edu
    User XXXXXX
    IdentityFile ~/.ssh/id_rsa_amarel
    ServerAliveInterval 5m
```
However if I do something like:
```
jupyter-forward --launch-command="srun [some command]" amarel
```

I am prompted for my password. Is there a way to avoid this? Perhaps this is related to #93?

### Edit

I should add that this command also prompts for a password:

```
jupyter-forward --launch-command="srun [some command]" --identity=".ssh/id_rsa_amarel" [username]@amarel.rutgers.edu
```

**Comment by mnlevy1981** [comment]
What version of `jupyter-forward` are you using? I would have thought that this was fixed in #51 but that's been on `main` for almost a year now so I suspect it's included in the version you are running. I can play with this a little bit over the next day or two and see if I can recreate the issue, but testing with a machine where I already have my ssh keys set up, I was not prompted for a password with

```
$ jupyter-forward --version
Jupyter Forward CLI Version: 2021.2.5
```

which I already had in a local environment, or

```
$ jupyter-forward --version
Jupyter Forward CLI Version: 2021.8.17
```

which is what I had after running `conda update jupyter-forward`

**Comment by andersy005** [comment]
Thank you for the report, @jessecusack! I'll look into it and will get back to you

**Comment by dcherian** [comment]
Hi Jesse,

`jupyter_forward` does not use `~/.ssh/config` (#93) so it won't see your custom key name. 

I think if you copied a `id_rsa` key (the default name) over to your cluster, it will work.

**Comment by jessecusack** [comment]
@mnlevy1981, @andersy005 

I am using version 2021.8.17.

**Comment by andersy005** [comment]
@jessecusack, 

it appears that your command may have a bug/typo in it 

```bash
jupyter-forward --launch-command="srun [some command]" --identity=".ssh/id_rsa_amarel"
```

You may want to provide the full path of the identify file i.e. `--identity="~/.ssh/id_rsa_amarel"` instead of `--identity=".ssh/id_rsa_amarel"`. Notice the `~/`.

**Comment by jessecusack** [comment]
@andersy005, I don't think that is the issue because I am still prompted for a password. If I put an incorrect identity path, I get an error. In fact, the path you suggest also gives an error:

```
Error: Invalid value for '--identity' / '-i': Path '~/.ssh/id_rsa_amarel' does not exist.
```

which would imply that jupyter-forward does not apply `expanduser` to the identity path string.

**Comment by andersy005** [comment]
@jessecusack, 

I tried diagnosing this issue today on a new machine and unfortunately, I wasn't able to reproduce the error. Your original configuration looks okay: 

```bash
Host amarel
    Hostname amarel.rutgers.edu
    User XXXXXX
    IdentityFile ~/.ssh/id_rsa_amarel
    ServerAliveInterval 5m
```

Can you confirm SSH is able to pick this configuration via


```bash
$ ssh amarel
```

???

**Comment by jessecusack** [comment]
@andersy005 

Since raising this issue I got a new laptop and now things 'just work'. I am not prompted for my password so presumably jupyer-forward must be using the identity file correctly. Thanks for troubleshooting!
