### ISSUE TITLE
Support for more shells

### ISSUE THREAD

**Issue by mnlevy1981** [ncar-xdev/jupyter-forward#135]
1. besides `tcsh` and `bash`, #133 makes it clear we need to support `sh` as well
2. Can we figure out remote shell from `$SHELL` (and raise exception mandating use of `--shell` if that variable is undefined)
3. one possible path forward would be to create a parent class that contains wrappers for running commands and then shell-specific child classes with correct functionality (e.g. `sh -l -c "[run this command]"` for `sh` and `bash` but `sh -c "[run this command]"` for `tcsh`; also `'{command} > {self.log_file} 2>&1'` for `sh` and `bash` but `'{command} >& {self.log_file}'` for `tcsh`)
4. May also need template for expanding variables (e.g. `hostname` in `'jupyter lab --no-browser --ip=\$(hostname -f)'`)

Ideally this would let us set up simple tests launching commands other than `jupyter` so that we can use Github Actions to run these tests and make sure we are supporting as many shells as possible (and that future PRs don't break existing support)

**Comment by kmpaul** [comment]
What is the real root of this problem?  Is it that `fabric`/`paramiko` doesn't let you forcefully execute remote commands in a different shell other than the user's default shell?  Why can't we execute all remote commands with `bash -c "{command}"`?

**Comment by mnlevy1981** [comment]
> What is the real root of this problem? Is it that `fabric`/`paramiko` doesn't let you forcefully execute remote commands in a different shell other than the user's default shell? For example, why couldn't we execute all remote commands with `bash -c "{command}"`?

`bash -c conda ...` requires a user to have run `conda init bash`, so it will fail for most `tcsh` users.

**Comment by kmpaul** [comment]
Ah!  I see the problem.  So you would need the user to specify something like a `--shell` option to use `conda activate` and run all commands in the user's native shell....  Hmm.

Doesn't `conda-incubator/setup-miniconda` activate conda without `conda init`?  Can't we do something like that?

**Comment by andersy005** [comment]
> Doesn't conda-incubator/setup-miniconda activate conda without conda init? Can't we do something like that?

During the conda setup, ` conda-incubator/setup-miniconda` invokes `conda init --all` to initialize all available shells

**Comment by kmpaul** [comment]
Hmm. I thought there was a way to manually source the conda init script.
