### ISSUE TITLE
Hanging on parsing 

### ISSUE THREAD

**Issue by rsignell-usgs** [ncar-xdev/jupyter-forward#148]
Tried `jupyter-forward` for the first time on our USGS HPC machine.   Was looking good, but then hung on the line:
```
 Parsing $HOME/.jupyter_forward/log_2022-03-21T07-51-39.txt log file on denali.cr.usgs.gov for jupyter information
 ```
 Full output:
 ```
$ jupyter-forward rsignell@denali --launch-command "srun -A woodshole -N 1 -t 00:30:00" --conda-env pangeo --port 8889
**************************************************** Authenticating ****************************************************Authenticating user (rsignell) from client (IGSAGIEGLTRSI10) to remote host (denali.cr.usgs.gov)
✅ The client is authenticated successfully
*********************************************** Verifying shell location ***********************************************✅ Using shell: /bin/bash
******************************************** Running jupyter sanity checks *********************************************/bin/bash -lc "source activate pangeo && which jupyter"
/home/rsignell/miniconda3/bin/jupyter
***************************************  Creating log file on denali.cr.usgs.gov ***************************************/bin/bash -lc "printenv TMPDIR"
/bin/bash -lc "printenv HOME"
/home/rsignell
/bin/bash -lc "touch $HOME/foobar && rm -rf $HOME/foobar && echo '$HOME is WRITABLE' || echo '$HOME is NOT WRITABLE'"
/home/rsignell is WRITABLE
/bin/bash -lc "mkdir -p $HOME/.jupyter_forward"
✅ Log directory is set to $HOME/.jupyter_forward
/bin/bash -lc "touch $HOME/.jupyter_forward/log_2022-03-21T07-51-39.txt"
✅ Log file is set to $HOME/.jupyter_forward/log_2022-03-21T07-51-39.txt
********************************************** Preparing Batch Job script **********************************************/bin/bash -lc "echo -n '#!' > $HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39"
/bin/bash -lc "echo /bin/bash -l >> $HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39"
/bin/bash -lc "echo 'source activate pangeo && jupyter lab --no-browser --ip=\$(hostname -f) > $HOME/.jupyter_forward/log_2022-03-21T07-51-39.txt 2>&1' >> $HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39"
/bin/bash -lc "chmod +x $HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39"
✅ Batch Job script resides in $HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39
************************************************ Launching Jupyter Lab *************************************************/bin/bash -c "srun -p compute -N 1 -t 00:30:00 $HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39"
🌨   Parsing $HOME/.jupyter_forward/log_2022-03-21T07-51-39.txt log file on denali.cr.usgs.gov for jupyter information   **************************** ❌ Terminated the network 📡 connection to denali.cr.usgs.gov *****************************
```
The log file looks like:
```
#!/bin/bash -l
source activate pangeo && jupyter lab --no-browser --ip=$(hostname -f) > /home/rsignell/.jupyter_forward/log_2022-03-21T
08-27-02.txt 2>&1

**Comment by kmpaul** [comment]
Hey, @rsignell-usgs!  What's in the `$HOME/.jupyter_forward/batch_job_script_2022-03-21T07-51-39` file on denali?

**Comment by kmpaul** [comment]
And what about `$HOME/.jupyter_forward/log_2022-03-21T07-51-39.txt`?

**Comment by rsignell-usgs** [comment]
@andersy005, I tried it -- no go: 
``` 
$  jupyter-forward rsignell@denali  --conda-env pangeo --port 8889
**************************************************** Authenticating ****************************************************
Authenticating user (rsignell) from client (IGSAGIEGLTRSI10) to remote host (denali.cr.usgs.gov)
✅ The client is authenticated successfully
*********************************************** Verifying shell location ***********************************************
✅ Using shell: /bin/bash
******************************************** Running jupyter sanity checks *********************************************
/bin/bash -lc "source activate pangeo && which jupyter"
/home/rsignell/miniconda3/bin/jupyter
***************************************  Creating log file on denali.cr.usgs.gov ***************************************
/bin/bash -lc "printenv TMPDIR"
/bin/bash -lc "printenv HOME"
/home/rsignell
/bin/bash -lc "touch $HOME/foobar && rm -rf $HOME/foobar && echo '$HOME is WRITABLE' || echo '$HOME is NOT WRITABLE'"
/home/rsignell is WRITABLE
/bin/bash -lc "mkdir -p $HOME/.jupyter_forward"
✅ Log directory is set to $HOME/.jupyter_forward
/bin/bash -lc "touch $HOME/.jupyter_forward/log_2022-03-22T12-40-09.txt"
✅ Log file is set to $HOME/.jupyter_forward/log_2022-03-22T12-40-09.txt
nid00038
************************************************ Launching Jupyter Lab *************************************************
/bin/bash -c "source activate pangeo && jupyter lab --no-browser --ip=nid00038 > $HOME/.jupyter_forward/log_2022-03-22T12-40-09.txt 2>&1"
```
And then it says it's parsing the log file, but the log file is empty.  

I'd be happy to screenshare/debug this.

**Comment by andersy005** [comment]
Thanks for trying!

> I'd be happy to screenshare/debug this.

I am available in the afternoon (2pm - 3pm Mountain Time). 

In the meantime, do you mind downgrading to jupyter-forward `v2022.1.15` and trying again? I'm starting to think that the log redirection changes introduced in #138 may have inadvertently broken other things.

**Comment by rsignell-usgs** [comment]
Tried the 2022.1.15 version, but still hanging on:
⛈  Parsing $HOME/.jupyter_forward/log.2022-03-22T13-12-21 log file on denali.cr.usgs.gov for jupyter information

**Comment by rsignell-usgs** [comment]
I could meet at 4pm ET = 2pm Mountain.   I'll send you a calendar invite.

**Comment by mnlevy1981** [comment]
I'd be happy to join the call as well, if that would be useful.

**Comment by andersy005** [comment]
@rsignell-usgs

> I could meet at 4pm ET = 2pm Mountain. I'll send you a calendar invite.

Did you send the invite to my UCAR address? I'm no longer employed at NCAR and that email account has been disabled

**Comment by andersy005** [comment]
We could use https://whereby.com/pangeo

**Comment by kmpaul** [comment]
How did this go?

**Comment by kmpaul** [comment]
I'll try it in a few minutes. My daughter is sick today, though, so I may not have much time.

**Comment by kmpaul** [comment]
I can verify that it hangs when trying to launch a JLab on Cheyenne.

**Comment by kmpaul** [comment]
I am going to try looking more closely at this today, assuming I have time.

**Comment by andersy005** [comment]
> I'll try it in a few minutes. My daughter is sick today, though, so I may not have much time.

Thank you for looking into this, @kmpaul! I hope she is feeling better

**Comment by kmpaul** [comment]
Thanks, @andersy005!  My daughter bounced back to life last night at 3:30am.  😄  So, I'm a bit tired, but everyone is well.

**Comment by rsignell-usgs** [comment]
I have some time now if we want to try live debug

**Comment by kmpaul** [comment]
I'm running to get some lunch.  Let me ping you in about 10 minutes.

**Comment by kmpaul** [comment]
Ok.  I'm now looking at this.  I'm not sure I know how to diagnose the problem, yet.  Hold on.

**Comment by kmpaul** [comment]
I've reproduced the problem on my end, and it appears to be caused by `jupyter lab --no-browser` command ending early.  So, when the parsing of the log file starts, the log file is empty and remains empty.

**Comment by rsignell-usgs** [comment]
@kmpaul that's great news for me -- means it not must a weird problem with our system!   So is there anything I can do to help, or just wait?

**Comment by kmpaul** [comment]
Well, at this point, I think it's a "just wait" thing.  I can't seem to figure out why the `jupyter lab` command is exiting early.  I'm trying to reproduce the entire workflow with straight SSH right now.

**Comment by andersy005** [comment]
@rsignell-usgs and @kmpaul, which version of `jupyterlab` are you running on the remote machine? I'm asking because I am unable to reproduce the issue using the following versions:

```bash
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.0.1
ipykernel        : 6.9.1
ipywidgets       : 7.6.5
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : 1.13.5
jupyterlab       : 3.2.9
nbclient         : 0.5.11
nbconvert        : 6.4.2
nbformat         : 5.1.3
notebook         : 6.4.8
qtconsole        : not installed
traitlets        : 5.1.1
```

**Comment by kmpaul** [comment]
I am using:

```bash
(pangeo) kpaul@cheyenne2:~> jupyter --version
Selected Jupyter core packages...
IPython          : 8.1.1
ipykernel        : 6.9.2
ipywidgets       : not installed
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : 1.15.6
jupyterlab       : 3.3.2
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.2.0
notebook         : 6.4.10
qtconsole        : not installed
traitlets        : 5.1.1
```

**Comment by kmpaul** [comment]
What version of paramiko and fabric are you using, @andersy005?

**Comment by kmpaul** [comment]
I am using `fabric 2.6.0` and `paramiko 2.10.3`.

**Comment by andersy005** [comment]
```bash
# Name                    Version                   Build  Channel
fabric                    2.6.0              pyhd8ed1ab_1    conda-forge
paramiko                  2.10.3             pyhd8ed1ab_0    conda-forge
```

**Comment by kmpaul** [comment]
What shell are you using on the remote system, @andersy005?

**Comment by kmpaul** [comment]
For me, it seems to be due to the Jupyter launch command being run with `/bin/bash -c` instead of `/bin/bash -lc`.

**Comment by kmpaul** [comment]
If I run the full command:

```
/bin/bash -c "conda activate pangeo && jupyter lab --no-browser --ip=cheyenne2.cheyenne.ucar.edu > $TMPDIR/.jupyter_forward/log_2022-03-24T13-28-45.txt 2>&1"
```

with vanilla SSH, it errors out saying that it can't find `conda`.  But if I change the command to:

```
/bin/bash -lc "conda activate pangeo && jupyter lab --no-browser --ip=cheyenne2.cheyenne.ucar.edu > $TMPDIR/.jupyter_forward/log_2022-03-24T13-28-45.txt 2>&1"
```

It works fine.  Makes sense.  You need a login shell to activate conda, right?

**Comment by kmpaul** [comment]
That's very weird. How is it that running `/bin/bash -c "conda activate"` works for you without the `-lc` flag?

**Comment by mnlevy1981** [comment]
> That's very weird. How is it that running `/bin/bash -c "conda activate"` works for you without the `-lc` flag?

I thought

1. The `-l` flag controls whether or not `.bash_profile` is sourced, but `.bashrc` is always sourced
1. `conda` was initialized in `.bashrc`

For me, I know (2) is true -- the following is in `.bashrc`:

```bash
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/glade/work/mlevy/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/glade/work/mlevy/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/glade/work/mlevy/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/glade/work/mlevy/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

**Comment by kmpaul** [comment]
Okay.  I just reverted my versions of `jupyter` to the following:

```
Selected Jupyter core packages...
IPython          : 8.1.1
ipykernel        : 6.9.2
ipywidgets       : not installed
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : 1.13.5
jupyterlab       : 3.2.9
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.2.0
notebook         : 6.4.10
qtconsole        : not installed
traitlets        : 5.1.1
```

And it still fails for me.  So, I don't think it has anything to do with the versions of jupyter on the remote system.

**Comment by kmpaul** [comment]
@mnlevy1981:  For me, I am using the system conda module, but the `module load conda` is being done in `.bashrc`.  So, I think we are both initializing conda in the same place.

However, it still doesn't explain my experiment.  Try running (from your laptop) the following command:

```
ssh kpaul@cheyenne.ucar.edu '/bin/bash -c "conda activate"'
```

and then run

```
ssh kpaul@cheyenne.ucar.edu '/bin/bash -lc "conda activate"'
```

The first version (without the `-l`) fails for me with:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

**Comment by kmpaul** [comment]
Okay.  Just so we can verify what SSH is doing, I did an experiment to see what files are being executed on the remote system.  I added `echo "READING BASHRC FILE"` to my `~/.bashrc` and `echo "READING PROFILE"` to my `~/.profile`.  Then I ran the previous two commands:

```
~> ssh kpaul@cheyenne.ucar.edu '/bin/bash -c "conda activate"'
Token_Response: 
READING BASHRC FILE

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

And then:

```
~> ssh kpaul@cheyenne.ucar.edu '/bin/bash -lc "conda activate"'
Token_Response: 
READING BASHRC FILE
READING BASHRC FILE
READING PROFILE
```

**Comment by kmpaul** [comment]
So, it ***is*** loading the `.bashrc` file both times.  (And, just for clarification, my `.profile` file is basically empty except for the `echo` command.)  With the `-l` option, it loads it twice.

So, something tells me that this must have something to do with using LMOD instead of a hand-installed `miniconda`.

**Comment by mnlevy1981** [comment]
> @mnlevy1981: For me, I am using the system conda module, but the `module load conda` is being done in `.bashrc`. So, I think we are both initializing conda in the same place.
> 
> However, it still doesn't explain my experiment. Try running (from your laptop) the following command:
> 
> ```
> ssh user@cheyenne.ucar.edu '/bin/bash -c "conda activate"'
> ```
> 
> and then run
> 
> ```
> ssh user@cheyenne.ucar.edu '/bin/bash -lc "conda activate"'
> ```

Oh, weird - I get the errors with `-c` but not with `-lc` as well... and I get the same behavior (`-lc` works, `-c` does not) on casper, which is really bizarre because I definitely tested the latest `jupyter-forward` code by running it on `casper`.

Regardless, isn't the latest version using `-lc` for everything except `csh` and `tcsh`? https://github.com/ncar-xdev/jupyter-forward/blob/main/jupyter_forward/core.py#L127

```python
        if 'csh' in self.shell:
            command = f'''{self.shell} -c "{command}"'''
        else:
            command = f'''{self.shell} -lc "{command}"'''
```

Unless the initial `conda` call isn't using `run_command`...

**Comment by kmpaul** [comment]
No.  There is a separate call on line 198:

https://github.com/ncar-xdev/jupyter-forward/blob/8e34462600699cae6e4a4bacbd31bfd35ab7af29/jupyter_forward/core.py#L198

**Comment by kmpaul** [comment]
> > @mnlevy1981: For me, I am using the system conda module, but the `module load conda` is being done in `.bashrc`. So, 
> Unless the initial `conda` call isn't using `run_command`...

Yep.  You guessed it.  😄

**Comment by kmpaul** [comment]
Seems like line 198 should be refactored to use `run_command` with the appropriate `kwargs`.

**Comment by mnlevy1981** [comment]
> No. There is a separate call on line 198:
> 
> https://github.com/ncar-xdev/jupyter-forward/blob/8e34462600699cae6e4a4bacbd31bfd35ab7af29/jupyter_forward/core.py#L198

So it looks like the solution is to modify that line

```diff
-  self.session.run(f'{self.shell} -c "{command}"', asynchronous=True, pty=True, echo=True)
+  self.run_command(command, asynchronous=True, pty=True, echo=True)
```

?

**Comment by kmpaul** [comment]
Yeah.  😄

**Comment by kmpaul** [comment]
I'm glad you were able to reproduce the error without using LMOD.  I was starting to think it had to have something to do with that...  Phew!

**Comment by kmpaul** [comment]
@mnlevy1981:  I don't think that change will work because of the `asynchronous=True` argument.  I think you cannot use `run_command` in this case.

**Comment by kmpaul** [comment]
Or, rather, you need to refactor the `run_command` to work with asynchronous execution.

**Comment by mnlevy1981** [comment]
Another option is to do something like

```python
        if 'csh' in self.shell:
            self.run_shell = f"{self.shell} -c"
        else:
            self.run_shell = f"{self.shell} -lc"
```

in `_check_shell()` and then both `run_command()` and `_launch_jupyter()` could rely on `f'{self.run_shell} "{command}"'`

**Comment by mnlevy1981** [comment]
(or a `self._get_run_command()` function that returns the proper string)

**Comment by kmpaul** [comment]
Yeah.  That might work.  I frankly don't know why `run_command(command, asynchronous=True)` fails.  It gives this error:

```
'Promise' object has no attribute 'exited'
```

At no point does the Jupyter-Forward code reference an `exited` attribute.

**Comment by andersy005** [comment]
Not sure if this is related but we do use the `failed` attribute here 

https://github.com/ncar-xdev/jupyter-forward/blob/8e34462600699cae6e4a4bacbd31bfd35ab7af29/jupyter_forward/core.py#L131-L132

**Comment by kmpaul** [comment]
Yeah.  You got it, @andersy005.  `out.failed` is a `parameter` method that executes a call sequence that eventually accesses `out.exited`, which is not defined on a `Promise` (only on a `Result`).

**Comment by kmpaul** [comment]
So, I think the proper solution to this is to change the `run_command()` function like so:

```diff
    def run_command(
        self,
        command,
        exit=True,
        warn=True,
        pty=True,
-       hide=None,
        echo=True,
+       asynchronous=False,
        **kwargs,
    ):
        if 'csh' in self.shell:
            command = f'''{self.shell} -c "{command}"'''
        else:
            command = f'''{self.shell} -lc "{command}"'''
-       out = self.session.run(command, warn=warn, pty=pty, hide=hide, echo=echo, **kwargs)
-       if out.failed and exit:
+       out = self.session.run(command, warn=warn, pty=pty, echo=echo, asynchronous=asynchronous, **kwargs)
+       if not asynchronous and exit and out.failed:
            sys.exit(1)
        return out
```

**NOTE:** The `hide` parameter can be removed because it defaults to the same default assumed by invoke's `run` method.

And then we can change L198 as you suggested @mnlevy1981:

```diff
-  self.session.run(f'{self.shell} -c "{command}"', asynchronous=True, pty=True, echo=True)
+  self.run_command(command, asynchronous=True)
```

This should fix the problem.  Agreed?  Does anyone see any problems with this?  If not, then I'll craft a PR.

**Comment by kmpaul** [comment]
I've started #152 to fix this.

**Comment by andreall** [comment]
Hi, 
I am getting the same error...jupyter-forward hangs on parsing. It was working well until Thursday-friday last week. I tried the 

> > @mnlevy1981: For me, I am using the system conda module, but the `module load conda` is being done in `.bashrc`. So, I think we are both initializing conda in the same place.
> > However, it still doesn't explain my experiment. Try running (from your laptop) the following command:
> > ```
> > ssh user@cheyenne.ucar.edu '/bin/bash -c "conda activate"'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then run
> > ```
> > ssh user@cheyenne.ucar.edu '/bin/bash -lc "conda activate"'
> > ```
> 
> Oh, weird - I get the errors with `-c` but not with `-lc` as well... and I get the same behavior (`-lc` works, `-c` does not) on casper, which is really bizarre because I definitely tested the latest `jupyter-forward` code by running it on `casper`.
> 
> Regardless, isn't the latest version using `-lc` for everything except `csh` and `tcsh`? https://github.com/ncar-xdev/jupyter-forward/blob/main/jupyter_forward/core.py#L127
> 
> ```python
>         if 'csh' in self.shell:
>             command = f'''{self.shell} -c "{command}"'''
>         else:
>             command = f'''{self.shell} -lc "{command}"'''
> `
> 
> Unless the initial `conda` call isn't using `run_command`...

And I get the same error. With -lc works, with -c it fails. 

On the Local machine:
> (base) aliraloarca@wilson ~ % jupyter-forward --version                            

> [Jupyter Forward CLI Version: 2022.9.10
> 
> (base) aliraloarca@wilson ~ % jupyter --version 
> Selected Jupyter core packages...
> IPython          : 8.17.2
> ipykernel        : 6.26.0
> ipywidgets       : 8.1.1
> jupyter_client   : 8.6.0
> jupyter_core     : 5.5.0
> jupyter_server   : 2.10.1
> jupyterlab       : 4.0.9
> nbclient         : 0.8.0
> nbconvert        : 7.11.0
> nbformat         : 5.9.2
> notebook         : 7.0.6
> qtconsole        : 5.5.1
> traitlets        : 5.13.0](url)
> 

On the remote machine:

> (base) wavewatch@ned:~> jupyter --version
> Selected Jupyter core packages...
> IPython          : 8.17.2
> ipykernel        : 6.26.0
> ipywidgets       : 8.1.1
> jupyter_client   : 8.6.0
> jupyter_core     : 5.5.0
> jupyter_server   : 2.10.1
> jupyterlab       : 4.0.9
> nbclient         : 0.8.0
> nbconvert        : 7.11.0
> nbformat         : 5.9.2
> notebook         : 7.0.6
> qtconsole        : 5.5.1
> traitlets        : 5.13.0

Any thoughts?
