### ISSUE TITLE
port forwarding failing on windows

### ISSUE THREAD

**Issue by rsignell-usgs** [ncar-xdev/jupyter-forward#81]
When I launch jupyter-forward to connect to our USGS HPC machines 
```
jupyter-forward rsignell@poseidon.whoi.edu --launch-command "srun -p compute -N 1 -t 00:30:00" --conda-env jupyter --port 8889
```
from an Anaconda prompt on Windows, there are no errors, but nothing loads in the new `http://localhost:8889` browser tab:  the connection is refused, so I guess the port forwarding is not working correctly. 

I can do port forwarding the old fashioned way from Windows, using git bash and :
```
 ssh -N -L 8889:`hostname`:8888 rsignell@poseidon.whoi.edu"
```
and I verified that the jupyter-forward invocation above works fine from Linux.   

Is there some other package I need to load into my custom conda environment on Windows to get things working?
Or something else I could do to help debug the problem?

**Comment by mnlevy1981** [comment]
When you specify `--port 8889`, it's going to forward to your local 8889 port. Does anything load in `http://localhost:8889`?

**Comment by rsignell-usgs** [comment]
@mnlevy1981 , oops, the 8888 above was a typo.  Indeed, nothing loads on http://localhost:8889 (when I specify port 8889).  The browser tab pops up, but connection is refused.

**Comment by rsignell-usgs** [comment]
Has anyone successfully used jupyter-forward on Windows?

**Comment by andersy005** [comment]
> Has anyone successfully used jupyter-forward on Windows?

Not that I know of. I am going to set up a windows VM to see if I can reproduce the issue, and figure out what's going on

**Comment by mnlevy1981** [comment]
> @mnlevy1981 , oops, the 8888 above was a typo (I just fixed it).
> Indeed, nothing loads on http://localhost:8889 (when I specify port 8889). The browser tab pops up, but connection is refused.

bummer! (I figured it was a typo, but was hoping for an easy fix :)

@andersy005 -- I have access to a windows machine at home and am happy to help test this as well. You might be better off on your own, though; I installed conda on it at some point to test things for our tutorials, but that's about the extent of my familiarity with scientific computing in Win10...

**Comment by andersy005** [comment]
Something strange is going on... I was able to create a VM with windows on it. Launching jupyter on a remote cluster with nodes with public IP addresses works: `jupyter-forward myusername@hobart.cgd.ucar.edu --no-port-forwarding`


Launching `jupyter` on the same cluster but enabling the port forwarding via `localhost` doesn't work: `jupyter-forward myusername@hobart.cgd.ucar.edu` 


In the first tab, you can see that everything is working fine when I access jupyter via the public IP address.

![Screen Shot 2021-04-20 at 3 18 40 PM](https://user-images.githubusercontent.com/13301940/115468683-a9ec7100-a1f0-11eb-8642-5b28905971f6.png)


When I check whether the (8888) port is in the `LISTENING` state on localhost, I get the following

![Screen Shot 2021-04-20 at 3 29 22 PM](https://user-images.githubusercontent.com/13301940/115468673-a6f18080-a1f0-11eb-9343-e52884587c25.png)

I will keep looking and will report back if I find something...

**Comment by rsignell-usgs** [comment]
@andersy005 , are there any Windows experts at NCAR? 
If not, perhaps @TomAugspurger could help us find someone!

**Comment by rsignell-usgs** [comment]
@ocefpaf, do you think one of the windows guys at conda-forge might know the answer here?

**Comment by rsignell-usgs** [comment]
@cgohlke, do you how how to address the Windows issue here?

**Comment by cgohlke** [comment]
Sorry, I don't have the setup to try this right now.

**Comment by rsignell-usgs** [comment]
It's worth mentioning again that this works fine on Windows:
* Windows: open an Anaconda command prompt terminal 
* Windows: type ` ssh denali.cr.usgs.gov`
* Denali (HPC): switch to a compute node (srun command)
* Denali:  type `jupyter lab --no-browser --ip=$HOST--port=$JPORT`

* Windows: open another Anaconda command prompt terminal 
* Windows: type  `ssh -N -L 8889:$HOST:$JPORT $USER@denali.cr.usgs.gov`
* Windows: open `localhost:8889`

**Comment by andersy005** [comment]
I now have access to a windows computer... I'll be looking into this in the coming days

**Comment by rsignell-usgs** [comment]
@andersy005, I'm guessing you are a tad busy, but just letting you know we are still very interested in getting this problem solved.

**Comment by andersy005** [comment]
@rsignell-usgs, thank you for your patience... I was on vacation for the last week. i still have this on my TODO list though, and i'm hoping to be able to report what i learn in tomorrow or thursday.

**Comment by andersy005** [comment]
i can confirm that i can reproduce this error on my local windows PC. i'm looking into what's going on exactly

**Comment by andersy005** [comment]
@rsignell-usgs, it turns out this is a known bug/issue in Fabric (the library we are using under the hood). For some reason, the tunneling doesn't work on windows

- https://github.com/fabric/fabric/issues/2102

it appears someone put together a fix. This hasn't been merged:

- https://github.com/fabric/fabric/pull/2221

**Comment by rsignell-usgs** [comment]
Tip:   As you can see above, I was able to activate my jupyter-forward environment in powershell, after doing:
```
powershell -ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\rsignell\miniconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\rsignell\miniconda3' "
```
But the Anaconda command prompt works fine also -- and perhaps therefore preferable unless there is a reason to use powershell.

**Comment by andersy005** [comment]
thank you for your patience, @rsignell-usgs! @ocefpaf, thank you for the patch! So glad to see this working...
